name: Deployment

on:
  push:
    branches: [ "develop", "uat", "master" ]
  pull_request:
    branches: [ "develop", "uat", "master" ]

jobs:
  build:
    name: Deployment
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        path: ./
            
    - name: Git Pull on Machine
      if: |
          github.ref == 'refs/heads/master' &&
          github.event_name == 'push'
      run: |
        cd ~/repo/My_Resume_Publish
        git pull
